=== fgrander/plc-dump-tools/python/src/plcexport/schemas/hardware.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "plcexport/hardware.schema.json",
  "title": "hardware.json (contract §7)",
  "type": "object",
  "required": [
    "controllers",
    "racks",
    "modules",
    "channels",
    "networks"
  ],
  "properties": {
    "controllers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ref",
          "name"
        ],
        "properties": {
          "ref": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "order_no": {
            "type": "string"
          },
          "firmware": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "racks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ref",
          "name"
        ],
        "properties": {
          "ref": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ref",
          "type"
        ],
        "properties": {
          "ref": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "rack": {
            "type": "string"
          },
          "slot": {
            "type": "integer"
          },
          "order_no": {
            "type": "string"
          },
          "firmware": {
            "type": "string"
          },
          "address_ranges": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": false
      }
    },
    "channels": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ref",
          "module_ref",
          "address"
        ],
        "properties": {
          "ref": {
            "type": "string"
          },
          "module_ref": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "networks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ref",
          "interface"
        ],
        "properties": {
          "ref": {
            "type": "string"
          },
          "interface": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "device_name": {
            "type": "string"
          },
          "subnet": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== fgrander/plc-dump-tools/samples/exports/myTiaProject1/PLC_1/hardware.json
{
  "channels": [],
  "controllers": [
    {
      "firmware": "V3.1",
      "name": "PLC_1",
      "order_no": "6ES7 517-3FP00-0AB0",
      "ref": "cpu:PLC_1"
    }
  ],
  "modules": [
    {
      "address_ranges": [
        "%I6.0-%I9.7"
      ],
      "order_no": "6ES7 134-4FB52-0AB0",
      "rack": "ET 200S-Station_1/2AI x U HS_1",
      "ref": "ET 200S-Station_1/2AI x U HS_1",
      "slot": 3,
      "type": "2AI x U HS_1"
    },
    {
      "address_ranges": [
        "%I4.0-%I4.7"
      ],
      "order_no": "6ES7 131-4BB01-0AB0",
      "rack": "ET 200S-Station_1/2DI x DC24V HF_1",
      "ref": "ET 200S-Station_1/2DI x DC24V HF_1",
      "slot": 2,
      "type": "2DI x DC24V HF_1"
    },
    {
      "firmware": "V5.0",
      "order_no": "6ES7 151-3AA22-0AB0",
      "rack": "ET 200S-Station_1/IO-Device_1",
      "ref": "ET 200S-Station_1/IO-Device_1",
      "slot": 0,
      "type": "IO-Device_1"
    },
    {
      "order_no": "6ES7 138-4CA01-0AA0",
      "rack": "ET 200S-Station_1/PM-E DC24V_1",
      "ref": "ET 200S-Station_1/PM-E DC24V_1",
      "slot": 1,
      "type": "PM-E DC24V_1"
    },
    {
      "address_ranges": [
        "%I10.0-%I25.7"
      ],
      "rack": "GSD-Geraet_1/16 Bytes Eingang_1",
      "ref": "GSD-Geraet_1/16 Bytes Eingang_1",
      "slot": 1,
      "type": "16 Bytes Eingang_1"
    },
    {
      "address_ranges": [
        "%Q4.0-%Q7.7"
      ],
      "rack": "GSD-Geraet_1/4 Bytes Ausgang_1",
      "ref": "GSD-Geraet_1/4 Bytes Ausgang_1",
      "slot": 2,
      "type": "4 Bytes Ausgang_1"
    },
    {
      "firmware": "B0",
      "order_no": "6ES7 158-0AD01-0XA0",
      "rack": "GSD-Geraet_1/Slave_1",
      "ref": "GSD-Geraet_1/Slave_1",
      "slot": 0,
      "type": "Slave_1"
    },
    {
      "firmware": "V0.0",
      "order_no": "6ES7 193-6AR00-0AA0",
      "rack": "PNPN Coupler/BA 2xRJ45",
      "ref": "PNPN Coupler/BA 2xRJ45",
      "slot": 127,
      "type": "BA 2xRJ45"
    },
    {
      "firmware": "V0.0",
      "order_no": "6ES7 193-6AR00-0AA0",
      "rack": "PNPN Coupler/BA 2xRJ45",
      "ref": "PNPN Coupler/BA 2xRJ45",
      "slot": 127,
      "type": "BA 2xRJ45"
    },
    {
      "firmware": "V3.0",
      "order_no": "6ES7 158-3AD01-0XA0",
      "rack": "PNPN Coupler/PNPN Coupler.X1",
      "ref": "PNPN Coupler/PNPN Coupler.X1",
      "slot": 0,
      "type": "PNPN Coupler.X1"
    },
    {
      "firmware": "V3.0",
      "order_no": "6ES7 158-3AD01-0XA0",
      "rack": "PNPN Coupler/PNPN Coupler.X2",
      "ref": "PNPN Coupler/PNPN Coupler.X2",
      "slot": 1,
      "type": "PNPN Coupler.X2"
    },
    {
      "firmware": "V0.0",
      "order_no": "6ES7 193-6AR00-0AA0",
      "rack": "PNPN Coupler_1/BA 2xRJ45",
      "ref": "PNPN Coupler_1/BA 2xRJ45",
      "slot": 127,
      "type": "BA 2xRJ45"
    },
    {
      "firmware": "V0.0",
      "order_no": "6ES7 193-6AR00-0AA0",
      "rack": "PNPN Coupler_1/BA 2xRJ45",
      "ref": "PNPN Coupler_1/BA 2xRJ45",
      "slot": 127,
      "type": "BA 2xRJ45"
    },
    {
      "firmware": "V6.0",
      "order_no": "6ES7 158-3AD10-0XA0",
      "rack": "PNPN Coupler_1/PNPN Coupler_1.X1",
      "ref": "PNPN Coupler_1/PNPN Coupler_1.X1",
      "slot": 0,
      "type": "PNPN Coupler_1.X1"
    },
    {
      "firmware": "V6.0",
      "order_no": "6ES7 158-3AD10-0XA0",
      "rack": "PNPN Coupler_1/PNPN Coupler_1.X2",
      "ref": "PNPN Coupler_1/PNPN Coupler_1.X2",
      "slot": 1,
      "type": "PNPN Coupler_1.X2"
    },
    {
      "firmware": "V3.1",
      "order_no": "6ES7 517-3FP00-0AB0",
      "rack": "S7-1500/ET200MP-Station_1/PLC_1",
      "ref": "S7-1500/ET200MP-Station_1/PLC_1",
      "slot": 1,
      "type": "PLC_1"
    },
    {
      "order_no": "6ES7 590-1***0-0AA0",
      "rack": "S7-1500/ET200MP-Station_1/Profilschiene_0",
      "ref": "S7-1500/ET200MP-Station_1/Profilschiene_0",
      "slot": 0,
      "type": "Profilschiene_0"
    },
    {
      "address_ranges": [
        "%I2.0-%I3.7"
      ],
      "order_no": "6ES7 321-1BH10-0AA0",
      "rack": "S7-300/ET200M-Station_1/DI 16x24VDC_1",
      "ref": "S7-300/ET200M-Station_1/DI 16x24VDC_1",
      "slot": 2,
      "type": "DI 16x24VDC_1"
    },
    {
      "address_ranges": [
        "%I0.0-%I1.7",
        "%Q0.0-%Q1.7"
      ],
      "order_no": "6ES7 327-1BH00-0AB0",
      "rack": "S7-300/ET200M-Station_1/DI 8/DX 8x24VDC_1",
      "ref": "S7-300/ET200M-Station_1/DI 8/DX 8x24VDC_1",
      "slot": 1,
      "type": "DI 8/DX 8x24VDC_1"
    },
    {
      "address_ranges": [
        "%Q2.0-%Q3.7"
      ],
      "order_no": "6ES7 322-1BH10-0AA0",
      "rack": "S7-300/ET200M-Station_1/DO 16x24VDC/0.5A_1",
      "ref": "S7-300/ET200M-Station_1/DO 16x24VDC/0.5A_1",
      "slot": 3,
      "type": "DO 16x24VDC/0.5A_1"
    },
    {
      "firmware": "V4.0",
      "order_no": "6ES7 153-4BA00-0XB0",
      "rack": "S7-300/ET200M-Station_1/IO-Device_3",
      "ref": "S7-300/ET200M-Station_1/IO-Device_3",
      "slot": 0,
      "type": "IO-Device_3"
    },
    {
      "order_no": "6ES7 390-1***0-0AA0",
      "rack": "S7-300/ET200M-Station_1/Profilschiene_0",
      "ref": "S7-300/ET200M-Station_1/Profilschiene_0",
      "slot": 0,
      "type": "Profilschiene_0"
    },
    {
      "firmware": "V4.6",
      "order_no": "6GK5 205-3BB00-2TB2",
      "rack": "SCALANCE XB-200/Switch_1",
      "ref": "SCALANCE XB-200/Switch_1",
      "slot": 0,
      "type": "Switch_1"
    }
  ],
  "networks": [
    {
      "address": "192.168.1.7/24",
      "device_name": "io-device_1",
      "interface": "Ethernet",
      "ref": "ET 200S-Station_1/IE1/Ethernet",
      "subnet": "PN/IE_1"
    },
    {
      "address": "3",
      "interface": "Profibus",
      "ref": "GSD-Geraet_1/PB1/Profibus",
      "subnet": "PROFIBUS_1"
    },
    {
      "address": "192.168.1.6/24",
      "device_name": "pnpn coupler.x1",
      "interface": "Ethernet",
      "ref": "PNPN Coupler/IE1/Ethernet",
      "subnet": "PN/IE_1"
    },
    {
      "address": "192.168.0.1/24",
      "device_name": "pnpn coupler.x2",
      "interface": "Ethernet",
      "ref": "PNPN Coupler/IE1/Ethernet",
      "subnet": "PN/IE_2"
    },
    {
      "address": "192.168.1.8/24",
      "device_name": "pnpn coupler_1.x1",
      "interface": "Ethernet",
      "ref": "PNPN Coupler_1/IE1/Ethernet",
      "subnet": "PN/IE_1"
    },
    {
      "address": "192.168.0.1/24",
      "device_name": "pnpn coupler_1.x2",
      "interface": "Ethernet",
      "ref": "PNPN Coupler_1/IE1/Ethernet"
    },
    {
      "address": "192.168.0.1/24",
      "device_name": "plc_1.profinet-schnittstelle_1",
      "interface": "Ethernet",
      "ref": "S7-1500/ET200MP-Station_1/X1/Ethernet"
    },
    {
      "address": "192.168.1.1/24",
      "device_name": "plc_1.profinet-schnittstelle_2",
      "interface": "Ethernet",
      "ref": "S7-1500/ET200MP-Station_1/X2/Ethernet",
      "subnet": "PN/IE_1"
    },
    {
      "address": "2",
      "interface": "Profibus",
      "ref": "S7-1500/ET200MP-Station_1/X3/Profibus",
      "subnet": "PROFIBUS_1"
    },
    {
      "address": "192.168.1.3/24",
      "device_name": "io-device_3",
      "interface": "Ethernet",
      "ref": "S7-300/ET200M-Station_1/IE1/Ethernet",
      "subnet": "PN/IE_1"
    },
    {
      "address": "192.168.1.4/24",
      "device_name": "switch_1",
      "interface": "Ethernet",
      "ref": "SCALANCE XB-200/IE1/Ethernet",
      "subnet": "PN/IE_1"
    }
  ],
  "racks": [
    {
      "name": "2AI x U HS_1",
      "ref": "ET 200S-Station_1/2AI x U HS_1"
    },
    {
      "name": "2DI x DC24V HF_1",
      "ref": "ET 200S-Station_1/2DI x DC24V HF_1"
    },
    {
      "name": "IO-Device_1",
      "ref": "ET 200S-Station_1/IO-Device_1"
    },
    {
      "name": "PM-E DC24V_1",
      "ref": "ET 200S-Station_1/PM-E DC24V_1"
    },
    {
      "name": "16 Bytes Eingang_1",
      "ref": "GSD-Geraet_1/16 Bytes Eingang_1"
    },
    {
      "name": "4 Bytes Ausgang_1",
      "ref": "GSD-Geraet_1/4 Bytes Ausgang_1"
    },
    {
      "name": "Slave_1",
      "ref": "GSD-Geraet_1/Slave_1"
    },
    {
      "name": "BA 2xRJ45",
      "ref": "PNPN Coupler/BA 2xRJ45"
    },
    {
      "name": "PNPN Coupler.X1",
      "ref": "PNPN Coupler/PNPN Coupler.X1"
    },
    {
      "name": "PNPN Coupler.X2",
      "ref": "PNPN Coupler/PNPN Coupler.X2"
    },
    {
      "name": "BA 2xRJ45",
      "ref": "PNPN Coupler_1/BA 2xRJ45"
    },
    {
      "name": "PNPN Coupler_1.X1",
      "ref": "PNPN Coupler_1/PNPN Coupler_1.X1"
    },
    {
      "name": "PNPN Coupler_1.X2",
      "ref": "PNPN Coupler_1/PNPN Coupler_1.X2"
    },
    {
      "name": "PLC_1",
      "ref": "S7-1500/ET200MP-Station_1/PLC_1"
    },
    {
      "name": "Profilschiene_0",
      "ref": "S7-1500/ET200MP-Station_1/Profilschiene_0"
    },
    {
      "name": "DI 16x24VDC_1",
      "ref": "S7-300/ET200M-Station_1/DI 16x24VDC_1"
    },
    {
      "name": "DI 8/DX 8x24VDC_1",
      "ref": "S7-300/ET200M-Station_1/DI 8/DX 8x24VDC_1"
    },
    {
      "name": "DO 16x24VDC/0.5A_1",
      "ref": "S7-300/ET200M-Station_1/DO 16x24VDC/0.5A_1"
    },
    {
      "name": "IO-Device_3",
      "ref": "S7-300/ET200M-Station_1/IO-Device_3"
    },
    {
      "name": "Profilschiene_0",
      "ref": "S7-300/ET200M-Station_1/Profilschiene_0"
    },
    {
      "name": "Switch_1",
      "ref": "SCALANCE XB-200/Switch_1"
    }
  ]
}

=== fgrander/plc-dump-tools/python/tests/fixtures/golden/export/tia_pid_v19/hardware.json
{
  "channels": [],
  "controllers": [
    {
      "firmware": "V3.1",
      "name": "LLCCA_PID_PLC",
      "order_no": "6ES7 510-1DK03-0AB0",
      "ref": "cpu:LLCCA_PID_PLC"
    }
  ],
  "modules": [
    {
      "firmware": "V0.0",
      "order_no": "6ES7 193-6AR00-0AA0",
      "rack": "ET 200SP station_1/BA 2xRJ45",
      "ref": "ET 200SP station_1/BA 2xRJ45",
      "slot": 127,
      "type": "BA 2xRJ45"
    },
    {
      "firmware": "V3.1",
      "order_no": "6ES7 510-1DK03-0AB0",
      "rack": "ET 200SP station_1/LLCCA_PID_PLC",
      "ref": "ET 200SP station_1/LLCCA_PID_PLC",
      "slot": 1,
      "type": "LLCCA_PID_PLC"
    },
    {
      "firmware": "V1.2",
      "order_no": "6ES7 193-6PA00-0AA0",
      "rack": "ET 200SP station_1/Server module_1",
      "ref": "ET 200SP station_1/Server module_1",
      "slot": 2,
      "type": "Server module_1"
    },
    {
      "firmware": "17.0.0.0",
      "order_no": "6AV2 124-0MC01-0AX0",
      "rack": "LLCCA_PID_HMI/LLCCA_PID_HMI",
      "ref": "LLCCA_PID_HMI/LLCCA_PID_HMI",
      "slot": 0,
      "type": "LLCCA_PID_HMI"
    }
  ],
  "networks": [
    {
      "address": "192.168.0.1/24",
      "device_name": "llcca_pid_plc",
      "interface": "Ethernet",
      "ref": "ET 200SP station_1/X1/Ethernet",
      "subnet": "PN/IE_1"
    },
    {
      "address": "1",
      "interface": "Mpi",
      "ref": "LLCCA_PID_HMI/PBMPI1/Mpi"
    },
    {
      "address": "192.168.0.3/24",
      "device_name": "llcca_pid_hmi",
      "interface": "Ethernet",
      "ref": "LLCCA_PID_HMI/X1/Ethernet",
      "subnet": "PN/IE_1"
    }
  ],
  "racks": [
    {
      "name": "BA 2xRJ45",
      "ref": "ET 200SP station_1/BA 2xRJ45"
    },
    {
      "name": "LLCCA_PID_PLC",
      "ref": "ET 200SP station_1/LLCCA_PID_PLC"
    },
    {
      "name": "Server module_1",
      "ref": "ET 200SP station_1/Server module_1"
    },
    {
      "name": "LLCCA_PID_HMI",
      "ref": "LLCCA_PID_HMI/LLCCA_PID_HMI"
    }
  ]
}

=== fgrander/plc-dump-tools/python/tests/fixtures/golden/export/s7_protected/hardware.json
{
  "channels": [],
  "controllers": [
    {
      "name": "CPU 315-2 PN/DP",
      "order_no": "6ES7 315-2EH14-0AB0",
      "ref": "cpu:CPU 315-2 PN/DP",
      "type": "Simatic300"
    }
  ],
  "modules": [
    {
      "order_no": "6ES7 315-2EH14-0AB0",
      "rack": "SIMATIC 300(1)/R0",
      "ref": "SIMATIC 300(1)/0.2",
      "slot": 2,
      "type": "CPU 315-2 PN/DP"
    },
    {
      "rack": "SIMATIC 300(1)/R0",
      "ref": "SIMATIC 300(1)/0.4",
      "slot": 4,
      "type": "CP 343-1"
    }
  ],
  "networks": [
    {
      "address": "192.168.0.10",
      "interface": "ethernet",
      "ref": "CPU 315-2 PN/DP/ethernet"
    },
    {
      "address": "2",
      "interface": "mpi",
      "ref": "CPU 315-2 PN/DP/mpi"
    }
  ],
  "racks": [
    {
      "name": "SIMATIC 300(1) rack 0",
      "ref": "SIMATIC 300(1)/R0"
    }
  ]
}
